team_emojis = {
    "Hawks": {"abbreviation": "ATL", "emoji": "🦅"},
    "Celtics": {"abbreviation": "BOS", "emoji": "🍀"},
    "Nets": {"abbreviation": "BKN", "emoji": "🏙"},
    "Hornets": {"abbreviation": "CHA", "emoji": "🐝"},
    "Bulls": {"abbreviation": "CHI", "emoji": "🐂"},
    "Cavaliers": {"abbreviation": "CLE", "emoji": "⚔️"},
    "Mavericks": {"abbreviation": "DAL", "emoji": "🐴"},
    "Nuggets": {"abbreviation": "DEN", "emoji": "⚒️"},
    "Pistons": {"abbreviation": "DET", "emoji": "🔧"},
    "Warriors": {"abbreviation": "GSW", "emoji": "🌁"},
    "Rockets": {"abbreviation": "HOU", "emoji": "🚀"},
    "Pacers": {"abbreviation": "IND", "emoji": "🏎️"},
    "Clippers": {"abbreviation": "LAC", "emoji": "⛵"},
    "Lakers": {"abbreviation": "LAL", "emoji": "🎥"},
    "Grizzlies": {"abbreviation": "MEM", "emoji": "🐻"},
    "Heat": {"abbreviation": "MIA", "emoji": "🔥"},
    "Bucks": {"abbreviation": "MIL", "emoji": "🦌"},
    "Timberwolves": {"abbreviation": "MIN", "emoji": "🐺"},
    "Pelicans": {"abbreviation": "NOP", "emoji": "⚜️"},
    "Knicks": {"abbreviation": "NYK", "emoji": "🗽"},
    "Thunder": {"abbreviation": "OKC", "emoji": "🌩️"},
    "Magic": {"abbreviation": "ORL", "emoji": "🪄"},
    "76ers": {"abbreviation": "PHI", "emoji": "🔔"},
    "Suns": {"abbreviation": "PHX", "emoji": "☀️"},
    "Trail Blazers": {"abbreviation": "POR", "emoji": "🗺"},
    "Kings": {"abbreviation": "SAC", "emoji": "👑"},
    "Spurs": {"abbreviation": "SAS", "emoji": "🤠"},
    "Raptors": {"abbreviation": "TOR", "emoji": "🦖"},
    "Jazz": {"abbreviation": "UTA", "emoji": "🎷"},
    "Wizards": {"abbreviation": "WAS", "emoji": "🧙‍♂️"}
}
